module Evergreen.Migrate.V7 exposing (..)

{-| This migration file was automatically generated by the lamdera compiler.

It includes:

  - A migration for each of the 6 Lamdera core types that has changed
  - A function named `migrate_ModuleName_TypeName` for each changed/custom type

Expect to see:

  - `Unimplementеd` values as placeholders wherever I was unable to figure out a clear migration path for you
  - `@NOTICE` comments for things you should know about, i.e. new custom type constructors that won't get any
    value mappings from the old type by default

You can edit this file however you wish! It won't be generated again.

See <https://dashboard.lamdera.app/docs/evergreen> for more info.

-}

import Dict
import Evergreen.V5.Audio
import Evergreen.V5.Character
import Evergreen.V5.Direction2d
import Evergreen.V5.EditorPage
import Evergreen.V5.Geometry.Types
import Evergreen.V5.Id
import Evergreen.V5.Keyboard
import Evergreen.V5.Match
import Evergreen.V5.MatchName
import Evergreen.V5.MatchPage
import Evergreen.V5.NetworkModel
import Evergreen.V5.NonemptySet
import Evergreen.V5.Point2d
import Evergreen.V5.Point3d
import Evergreen.V5.Route
import Evergreen.V5.Shape
import Evergreen.V5.Size
import Evergreen.V5.Sounds
import Evergreen.V5.TextMessage
import Evergreen.V5.Textures
import Evergreen.V5.Timeline
import Evergreen.V5.Types
import Evergreen.V5.Vector2d
import Evergreen.V5.Vector3d
import Evergreen.V7.Audio
import Evergreen.V7.Character
import Evergreen.V7.Direction2d
import Evergreen.V7.EditorPage
import Evergreen.V7.Geometry.Types
import Evergreen.V7.Id
import Evergreen.V7.Keyboard
import Evergreen.V7.Match
import Evergreen.V7.MatchName
import Evergreen.V7.MatchPage
import Evergreen.V7.NetworkModel
import Evergreen.V7.NonemptySet
import Evergreen.V7.Point2d
import Evergreen.V7.Point3d
import Evergreen.V7.Route
import Evergreen.V7.Shape
import Evergreen.V7.Size
import Evergreen.V7.Sounds
import Evergreen.V7.TextMessage
import Evergreen.V7.Textures
import Evergreen.V7.Timeline
import Evergreen.V7.Types
import Evergreen.V7.Vector2d
import Evergreen.V7.Vector3d
import Lamdera.Migrations exposing (..)
import List
import List.Nonempty
import Maybe
import Quantity
import Result
import SeqDict
import SeqSet


frontendModel : Evergreen.V5.Types.FrontendModel -> ModelMigration Evergreen.V7.Types.FrontendModel Evergreen.V7.Types.FrontendMsg
frontendModel old =
    ModelReset


backendModel : Evergreen.V5.Types.BackendModel -> ModelMigration Evergreen.V7.Types.BackendModel Evergreen.V7.Types.BackendMsg
backendModel old =
    ModelReset


frontendMsg : Evergreen.V5.Types.FrontendMsg -> MsgMigration Evergreen.V7.Types.FrontendMsg Evergreen.V7.Types.FrontendMsg
frontendMsg old =
    MsgOldValueIgnored


toBackend : Evergreen.V5.Types.ToBackend -> MsgMigration Evergreen.V7.Types.ToBackend Evergreen.V7.Types.BackendMsg
toBackend old =
    MsgOldValueIgnored


backendMsg : Evergreen.V5.Types.BackendMsg -> MsgMigration Evergreen.V7.Types.BackendMsg Evergreen.V7.Types.BackendMsg
backendMsg old =
    MsgOldValueIgnored


toFrontend : Evergreen.V5.Types.ToFrontend -> MsgMigration Evergreen.V7.Types.ToFrontend Evergreen.V7.Types.FrontendMsg
toFrontend old =
    MsgOldValueIgnored
